-- ⏸️ PENDIENTE — ESCRITA, **NO APLICADA**, Y A PROPÓSITO FUERA DE `migrations/`
--
-- ═══ POR QUÉ VIVE ACÁ Y NO EN `supabase/migrations/` ═══════════════════════
-- Un archivo en `migrations/` que no está aplicado **es drift** — y el drift
-- en cero es exactamente lo que se verifica al cerrar cada tanda. *Un
-- pendiente disfrazado de migración envenena el instrumento que lo detectaría.*
-- Cuando se aplique, se MUEVE a `migrations/` con su timestamp y se registra.
--
-- ═══ 🔴 SU DISPARO — CORREGIDO, Y LA CORRECCIÓN ES LA PARTE IMPORTANTE ═════
--
-- **La primera versión de este archivo decía que el disparo era el MERGE de la
-- pantalla de C. Es FALSO, y se corrige acá en vez de dejarlo convivir.**
--
-- > ***Lo que tiene que dejar de poder llamar a la forma vieja no es el REPO:
-- > es el BUNDLE.*** Un merge no cambia lo que corre en el teléfono. Entre el
-- > merge y el publish, el aparato del founder sigue ejecutando el alta vieja
-- > —la que manda solo `nombre · documento · teléfono`— y el guard la rebotaría
-- > igual que si no se hubiera mergeado nada.
--
-- **EL ORDEN QUE RIGE, en cuatro pasos y en este orden:**
--   ① C exige los dos campos en su CTA (commit)
--   ② A mergea
--   ③ **A PUBLICA el OTA y lo CONFIRMA APLICADO en el aparato** (§6bis-B)
--   ④ **recién entonces** A aplica este guard
--
-- El paso ③ no es ceremonia: es el único que mueve el bundle. Saltarlo deja la
-- ventana abierta con otro nombre.
--
-- ⚠️ Y queda una ventana residual que se declara en vez de taparse: entre ③ y
-- ④ un dispositivo que todavía no bajó el OTA sigue con la forma vieja. Con un
-- solo aparato es controlable —se confirma en pantalla y se sigue—; **el día
-- que haya vendedores reales, este guard se aplica con el OTA ya asentado**,
-- no el mismo minuto.
--
-- ═══ CÓMO VERIFICAR QUE YA SE PUEDE APLICAR (dos preguntas, las dos medibles)
--   ① ¿`main` tiene la pantalla nueva?
--        grep -rn "foto_path" apps/prestador/src/app/ventas/configuracion.tsx \
--                             apps/prestador/src/components/alta/PasoEquipo.tsx
--      Si los DOS llamadores mandan foto y whatsapp ⇒ ①  ✅
--   ② ¿el OTA con esa pantalla está APLICADO en el aparato?
--        Cuenta › el pie: el `updateId` en PANTALLA contra el group publicado.
--      *No alcanza con que el publish haya salido: L-138 — el gate empieza
--       confirmando qué está corriendo, no qué se subió.* **Manda ②.**
--
-- ═══ QUÉ QUEDA OBLIGATORIO — decidido contra el literal, no por gusto ═══════
-- La spec del founder marca **DOS** con esas palabras: *«foto del repartidor,
-- **obligatoria**»* y *«WhatsApp **no opcional**»*. ⇒ `foto_path` y `whatsapp`.
--
-- **`tipo_documento` NO, y la razón es un modo de falla real:** declararlo
-- **activa la validación contra la máscara del catálogo**. Si además fuera
-- obligatorio, una persona con un documento que no encaja en ninguna de las
-- tres máscaras —formato viejo, documento extranjero— quedaría **imposible de
-- registrar**. Opcional, valida cuando se declara; obligatorio, bloquea a
-- quien vino a trabajar. *La calidad del dato no puede costar un repartidor.*
--
-- **`documento_foto_path` NO:** el literal no lo marca, y su función es
-- pre-llenar por extracción — un MEDIO, no un fin. Exigir dos fotos duplica la
-- fricción del mostrador sin ganancia declarada.
--
-- ⇒ Si el founder quiere cualquiera de los dos obligatorio, es una línea más
--   acá y el mismo tren. Se declara para que sea una decisión y no un olvido.
--
-- ═══ NOT NULL: **NO**, y está MEDIDO ═══════════════════════════════════════
-- `repartidores` tiene **4 filas vivas (3 activas)** y las **4 tienen los
-- CUATRO campos nuevos en NULL**. Un `NOT NULL` exige backfill, y **la foto de
-- una persona no se puede backfillear**: no existe. ⇒ la obligatoriedad vive
-- en la puerta, que es donde C la pidió.

BEGIN;

-- El guard va DENTRO de `registrar_repartidor`, justo después del de
-- `documento_requerido`. Se aplica por empalme sobre la definición VIVA
-- (jamás sobre una copia de este archivo, que para entonces estará vieja).
--
--   IF p_foto_path IS NULL OR length(btrim(p_foto_path)) = 0 THEN
--     RAISE EXCEPTION 'foto_requerida' USING ERRCODE = '22023';
--   END IF;
--   IF p_whatsapp IS NULL OR length(btrim(p_whatsapp)) = 0 THEN
--     RAISE EXCEPTION 'whatsapp_requerido' USING ERRCODE = '22023';
--   END IF;
--
-- ⚠️ **`actualizar_repartidor` NO lleva el guard**, y es deliberado: las 4
-- filas previas a S98 nacieron sin foto ni WhatsApp, y exigirlos al ACTUALIZAR
-- volvería **incorregible** a un repartidor viejo — no se le podría ni apagar
-- el `activo` sin antes completarle una foto que quizás nadie tiene.
-- *Un guard que impide arreglar lo que ya está mal no protege: atrapa.*

-- ── El cinturón que esta migración va a necesitar cuando se aplique ────────
-- ① rojo: un alta sin foto rebota `foto_requerida`
-- ② rojo: un alta sin whatsapp rebota `whatsapp_requerido`
-- ③ verde: el alta completa sigue entrando
-- ④ 🔴 verde de control, EL QUE IMPORTA: `actualizar_repartidor` sobre uno de
--    los 4 viejos (sin foto) SIGUE funcionando — si este brazo se pone rojo,
--    el guard se filtró donde no iba y hay 4 repartidores incorregibles.

ROLLBACK; -- este archivo NO se aplica tal cual: es la letra del pendiente.
