begin;
-- ① «Cobaya o Cuy» sale de roedor: la especie `cobaya` ya tiene sus cinco
-- variedades reales. Medido: CERO mascotas la declaran. Su ficha se va por
-- cascade y era la vacía por raza no reconocida — el modelo se había negado a
-- escribir sobre ella, con razón: es un nombre genérico, no una raza.
delete from public.cat_razas where especie='roedor' and slug='cobaya-o-cuy';

-- ② LAS TRES PRIMERAS PUBLICADAS DE LA HISTORIA DEL PRODUCTO.
-- El founder las leyó una por una y dijo que sí. El CHECK exige revisor Y
-- fecha para poder prender `activo`: **no existe forma de publicar sin firma**.
update public.razas_contenido
   set activo = true,
       revisado_por = '75d0798a-ea90-4a97-a2f2-74f3234d892a'::uuid,
       revisado_en = now()
 where raza_codigo in ('bulldog-ingles','american-bully','maine-coon');

-- ③ «chicos» → «niños»: la voz de la casa es tuteo NEUTRO y «chicos» es
-- rioplatense; en Ecuador se dice «niños».
-- 🔴 EL REEMPLAZO NO ES CIEGO, Y ESA ES TODA LA CURA: «chicos» significa
-- TAMBIÉN «pequeños», y cinco fichas lo usan así — «espacios chicos» en
-- bulldog-frances y pekines, «grupos muy chicos» en tetra-neon, y dos más en
-- `predisposiciones` («espacios muy chicos», «grupos muy chicos»). Un
-- find-and-replace habría escrito «espacios niños» y nadie lo habría visto
-- hasta que una familia leyera la ficha. Se tocan SÓLO las 23 donde significa
-- niños, y `predisposiciones` no se toca en absoluto.
update public.razas_contenido set temperamento='Suele ser un perro cariñoso y apegado a su familia, con buena disposición hacia los niños cuando se lo socializa bien. Es sociable y busca compañía humana, aunque como cualquier perro necesita aprender a convivir con otros animales desde cachorro. El carácter final depende mucho de la crianza y la genética individual.' where especie='perro' and raza_codigo='american-bully';
update public.razas_contenido set temperamento='Suele ser un perro tranquilo, afectuoso y muy apegado a su familia. Tiende a ser bueno con niños y con otros animales si se socializa desde cachorro, aunque puede ser algo reservado con extraños. Le gusta estar cerca de las personas y no lleva bien quedarse solo por mucho tiempo.' where especie='perro' and raza_codigo='bernese';
update public.razas_contenido set temperamento='Suele ser alegre, cariñoso y muy apegado a su familia. Le gusta estar acompañado y participar de la vida en casa, aunque algunos ejemplares pueden mostrarse un poco ansiosos si se quedan solos por mucho tiempo. Es sociable con otros perros y con niños cuando se lo socializa desde cachorro.' where especie='perro' and raza_codigo='bichon-frise';
update public.razas_contenido set temperamento='Suele ser un perro alegre, sociable y apegado a su familia. Tiende a llevarse bien con niños y con otros animales cuando se lo socializa desde cachorro. Es despierto y disfruta del contacto humano, aunque cada individuo tiene su propio carácter.' where especie='perro' and raza_codigo='boston-terrier';
update public.razas_contenido set temperamento='Suele ser un perro enérgico, juguetón y muy apegado a su familia, incluso ya de adulto conserva actitudes de cachorro. Tiende a ser protector sin ser agresivo, aunque necesita socialización temprana para llevarse bien con otros animales y desconocidos. Con los niños de la casa generalmente es paciente y activo compañero de juegos.' where especie='perro' and raza_codigo='boxer';
update public.razas_contenido set temperamento='Suele ser un gato tranquilo, independiente y de trato afable, que no demanda atención constante pero disfruta de la compañía de su familia. Tiende a ser paciente con los niños y con otros animales, aunque cada ejemplar tiene su propio carácter. No es especialmente activo, así que agradece que se lo estimule a moverse.' where especie='gato' and raza_codigo='british-shorthair';
update public.razas_contenido set temperamento='Suele ser cariñoso, tranquilo y muy apegado a su familia. Tiende a tener poca energía y a disfrutar de estar cerca de las personas más que de correr o jugar mucho. Con otros perros y con niños generalmente es paciente, aunque cada animal tiene su carácter.' where especie='perro' and raza_codigo='bulldog-ingles';
update public.razas_contenido set temperamento='Suele ser un perro cariñoso, sociable y con muchas ganas de estar cerca de su familia. Se adapta bien a la vida en departamento y generalmente lleva bien la convivencia con niños y otros animales. Como cualquier perro, necesita socialización temprana para desarrollar confianza.' where especie='perro' and raza_codigo='charles-spaniel';
update public.razas_contenido set temperamento='Suele ser un perro alegre, afectuoso y muy apegado a su familia. Tiende a llevarse bien con niños y con otros animales si se socializa desde cachorro. Algunos ejemplares pueden mostrarse sensibles o algo nerviosos si les falta estimulación o compañía.' where especie='perro' and raza_codigo='cocker-spaniel';
update public.razas_contenido set temperamento='Suele ser un perro activo, alerta y muy apegado a su familia. Con buena socialización desde cachorro se lleva bien con niños y otros animales, aunque algunos pueden mostrarse reservados con extraños. Necesita estímulo físico y mental porque tiende a aburrirse con facilidad.' where especie='perro' and raza_codigo='dalmata';
update public.razas_contenido set temperamento='Suele ser un gato curioso, activo y muy apegado a su familia, buscando participar en todo lo que pasa en la casa. Tiende a ser sociable con otras mascotas y con niños, y le gusta trepar y observar desde lugares altos. Algunos ejemplares son bastante habladores y demandantes de atención.' where especie='gato' and raza_codigo='devon-rex';
update public.razas_contenido set temperamento='Suele ser un perro sociable, paciente y con muchas ganas de agradar. Se lleva bien con niños y con otros animales, aunque como cualquier perro necesita aprender límites desde cachorro. Es activo y disfruta del contacto con la gente, por lo que no le sienta bien pasar mucho tiempo solo.' where especie='perro' and raza_codigo='golden-retriever';
update public.razas_contenido set temperamento='Suele ser un perro tranquilo y cariñoso dentro de casa, a pesar de su porte imponente. Tiende a encariñarse mucho con su familia y a llevarse bien con los niños si se socializa desde cachorro. Como cualquier perro grande, conviene enseñarle buenos modales temprano porque después cuesta más corregir hábitos.' where especie='perro' and raza_codigo='gran-danes';
update public.razas_contenido set temperamento='Suele ser un perro sociable, activo y con muchas ganas de agradar, lo que lo hace bastante fácil de entrenar. Tiene buena disposición para convivir con niños y con otros animales, aunque como cualquier perro necesita socialización temprana. Es enérgico y disfruta mucho del contacto con la familia, así que puede sufrir si pasa demasiado tiempo solo.' where especie='perro' and raza_codigo='labrador-retriever';
update public.razas_contenido set temperamento='Suele ser un gato sociable y tranquilo, que disfruta estar cerca de su familia sin ser demandante. Muchos son curiosos y juguetones hasta grandes edades, y se llevan bien con otros animales y con niños. No suele maullar mucho, aunque tiene un repertorio de sonidos particular.' where especie='gato' and raza_codigo='maine-coon';
update public.razas_contenido set temperamento='Suele ser un conejo tranquilo y sociable, que se adapta bien a la vida en interior. Muchos disfrutan del contacto humano y del manejo diario si se los acostumbra de niños. Como todo conejo, necesita tiempo para confiar y espacio propio donde sentirse seguro.' where especie='conejo' and raza_codigo='mini-lop';
update public.razas_contenido set temperamento='Suele ser un perro leal, atento y con mucha disposición para aprender. Necesita estímulo mental y una familia que le dedique tiempo, porque si se aburre puede volverse ansioso o destructivo. Con buena socialización se lleva bien con niños y otros animales, aunque puede mostrarse reservado con desconocidos.' where especie='perro' and raza_codigo='pastor-aleman';
update public.razas_contenido set temperamento='Suele ser un perro sociable, apegado a su familia y con ganas de estar cerca de la gente. Tiende a llevarse bien con niños y con otros animales, aunque como en toda raza el carácter también depende de la crianza y la socialización. Puede ser algo testarudo a la hora de entrenar, pero responde bien a la paciencia y los estímulos positivos.' where especie='perro' and raza_codigo='pug';
update public.razas_contenido set temperamento='Suele ser un gato calmo y apegado a su familia, que busca estar cerca de las personas más que trepar o esconderse. Muchos se dejan cargar y manipular con facilidad, aunque esto varía según el individuo. Convive bien con otros animales y con niños cuando se lo trata con respeto.' where especie='gato' and raza_codigo='ragdoll';
update public.razas_contenido set temperamento='Suele ser un perro sociable, alegre y muy apegado a su familia, con tendencia a no querer quedarse solo por mucho tiempo. Es activo y necesita estímulo, aunque también disfruta del contacto humano y busca estar cerca de las personas. Con otros perros y con niños suele llevarse bien si tuvo buena socialización.' where especie='perro' and raza_codigo='samoyedo';
update public.razas_contenido set temperamento='Suele ser un perro tranquilo, paciente y cariñoso con su familia, incluido con los niños. No es de los más activos ni ladradores, y tiende a ser calmo dentro de la casa a pesar de su tamaño. Como cualquier perro, necesita socialización desde cachorro para desenvolverse bien con otras personas y animales.' where especie='perro' and raza_codigo='san-bernardo';
update public.razas_contenido set temperamento='Suelen ser gatos tranquilos y adaptables, que disfrutan del contacto con su familia sin ser demasiado demandantes. Muchos se llevan bien con niños y otros animales si la convivencia se da de forma gradual. Como en toda raza, el carácter individual puede variar bastante.' where especie='gato' and raza_codigo='scottish-fold';
update public.razas_contenido set temperamento='Suele ser una raza afectuosa y muy apegada a su familia, incluyendo a los niños, con quienes tiende a mostrarse paciente y juguetón. Puede tener un carácter fuerte y necesita límites claros desde cachorro. Con otros perros conviene ir con cuidado y una socialización temprana, ya que no todos los ejemplares toleran bien la convivencia con perros desconocidos.' where especie='perro' and raza_codigo='staffordshire-bull-terrier';
commit;
